<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Adg.QuranicGrammar</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adg.QuranicCore\Adg.QuranicCore.csproj" />
    <ProjectReference Include="..\Adg.QuranicCorpus\Adg.QuranicCorpus.csproj" />
  </ItemGroup>
</Project>
